export const REQUEST_SEARCH_AUTOCOMPLETE = 'REQUEST_SEARCH_AUTOCOMPLETE';
export const RECEIVE_SEARCH_RESULTS      = 'RECEIVE_SEARCH_RESULTS';

export const REQUEST_DEST_AUTOCOMPLETE = 'REQUEST_DEST_AUTOCOMPLETE';
export const RECEIVE_DEST_AUTOCOMPLETE_RESULTS = 'RECEIVE_DEST_AUTOCOMPLETE_RESULTS';

export const CHANGE_NATIONAL_TYPE = 'CHANGE_NATIONAL_TYPE';

export const CHANGE_CURRENCY_UNIT = 'CHANGE_CURRENCY_UNIT';

export const FETCH_DECK = 'FETCH_DECK';

export const REQUEST_CITIES_FETCHING = 'REQUEST_CITIES_FETCHING';

export const REMOVE_SEARCH_RESULTS = 'REMOVE_SEARCH_RESULTS';

export const CHANGE_LOCALE = 'CHANGE_LOCALE';

export const CHANGE_MENU_OPTIONS = 'CHANGE_MENU_OPTIONS';

export const SET_AUTOCOMPLETE_FROM_VALUE = 'SET_AUTOCOMPLETE_FROM_VALUE';

export const SET_AUTOCOMPLETE_TO_VALUE = 'SET_AUTOCOMPLETE_TO_VALUE';

export const SEARCH_DATE_VALUE = 'SEARCH_DATE_VALUE';

export const ADD_COUNT_TRAVELLER = 'ADD_COUNT_TRAVELLER';
export const REDUCE_COUNT_TRAVELLER = 'REDUCE_COUNT_TRAVELLER';

export const SELECT_TRAVELLER_CLASS = 'SELECT_TRAVELLER_CLASS';

export const DEFAULT_VALUE_SEARCH_COMPONENTS = 'DEFAULT_VALUE_SEARCH_COMPONENTS';

export const SEARCH_DATE_FROM_VALUE = 'SEARCH_DATE_FROM_VALUE';

export const SEARCH_DATE_TO_VALUE = 'SEARCH_DATE_TO_VALUE';

export const CHANGE_NATION_TYPE = 'CHANGE_NATION_TYPE';

export const CHANGE_TRIP_PLAN = 'CHANGE_TRIP_PLAN';

export const SWAP_SEARCH_VALUE = 'SWAP_SEARCH_VALUE';

export const SEARCH_ONEWAY_DATE_VALUE = 'SEARCH_ONEWAY_DATE_VALUE';

export const SELECT_TRAVELLER_COUNT = 'SELECT_TRAVELLER_COUNT';

export const IS_REFRESING_STATE = 'IS_REFRESING_STATE';
export const IS_REFRESING_STATE_END = 'IS_REFRESING_STATE_END';

export const REQUEST_HOTEL_AUTOCOMPLETE = 'REQUEST_HOTEL_AUTOCOMPLETE';
export const RECEIVE_SEARCH_HOTEL_RESULTS = 'RECEIVE_SEARCH_HOTEL_RESULTS';
export const REQUEST_SEARCH_HOTEL_RESULTS = 'REQUEST_SEARCH_HOTEL_RESULTS';

export const RECEIVE_SEARCH_ERROR = 'RECEIVE_SEARCH_ERROR';
export const REMOVE_HOTEL_RESULTS = 'REMOVE_HOTEL_RESULTS';


export const SELECT_DESTINATION_VALUE = 'SELECT_DESTINATION_VALUE';

export const ADD_AGE_SELECTOR = 'ADD_AGE_SELECTOR';
export const REDUCE_AGE_SELECTOR = 'REDUCE_AGE_SELECTOR';

export const SELECT_CHILD_AGE = 'SELECT_CHILD_AGE';

export const SELECT_TOUR_DESTINATION = 'SELECT_TOUR_DESTINATION';

export const CHANGE_FIRST_NAME = 'CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = 'CHANGE_LAST_NAME';
export const CHANGE_GENDER = 'CHANGE_GENDER';
export const CHANGE_NATION = 'CHANGE_NATION';
export const CHANGE_DATE_OF_BIRTH = 'CHANGE_DATE_OF_BIRTH';
export const SET_VISA_DEFAULT_VALUE = 'SET_VISA_DEFAULT_VALUE';
export const LOAD_DEFAULT_VALUES = 'LOAD_DEFAULT_VALUES';

export const UPDATE_PROMOTION_SHOW = 'UPDATE_PROMOTION_SHOW';
export const CLOSE_PROMOTION_SHOW = 'CLOSE_PROMOTION_SHOW';

export const REFRESH_PAYMENT = 'REFRESH_PAYMENT';
export const SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE';


export const GET_FLIGHTS = 'GET_FLIGHTS';
export const RECEIVE_FLIGHT_RESULTS = 'RECEIVE_FLIGHT_RESULTS';
export const RECEIVE_NOT_FOUND_FLIGHTS = 'RECEIVE_NOT_FOUND_FLIGHTS';
export const FILTER_FLIGHT_RETURN='FILTER_FLIGHT_RETURN';
export const FILTER_FLIGHTS = 'FILTER_FLIGHTS';
export const SORT_FLIGHTS = 'SORT_FLIGHTS';
export const SORT_FILTERED_FLIGHTS = 'SORT_FILTERED_FLIGHTS';
export const SELECT_FLIGHT = 'SELECT_FLIGHT';
export const LOAD_MORE_FLIGHT = 'LOAD_MORE_FLIGHT';
export const LOAD_MORE_FLIGHT_RETURN ='LOAD_MORE_FLIGHT_RETURN';
export const VERIFY_FLIGHT= 'VERIFY_FLIGHT';
export const RECEIVE_VERIFY_FLIGHT = 'RECEIVE_VERIFY_FLIGHT';
export const CONFIRM_FLIGHT = "CONFIRM_FLIGHT";
export const RECEIVE_CONFIRM_FLIGHT="RECEIVE_CONFIRM_FLIGHT";

export const GET_HOTELS = 'GET_HOTELS';
export const RECEIVE_HOTEL_RESULTS = 'RECEIVE_HOTEL_RESULTS';
export const RECEIVE_HOTEL_ERROR = 'RECEIVE_HOTEL_ERROR';

export const LOAD_MORE_HOTELS = 'LOAD_MORE_HOTELS'
export const NOT_FOUND_HOTELS = 'NOT_FOUND_HOTELS';

export const FILTER_HOTELS = 'FILTER_HOTELS';
export const SORT_HOTELS = 'SORT_HOTELS';
export const SORT_FILTERED_HOTELS = 'SORT_FILTERED_HOTELS';
export const SELECT_HOTEL = 'SELECT_HOTEL';
export const GET_HOTEL_DETAIL = 'GET_HOTEL_DETAIL';
export const RECEIVE_HOTEL_DETAIL = 'RECEIVE_HOTEL_DETAIL';
export const GET_HOTEL_FILTERS = 'GET_HOTEL_FILTERS';
export const RECEIVE_HOTEL_FILTERS = 'RECEIVE_HOTEL_FILTERS';

//hotel reservation actions
export const ADD_ROOM = 'ADD_ROOM';
export const ADD_EXTRA_BED = 'ADD_EXTRA_BED';
export const APPEND_ROOM = 'APPEND_ROOM';
export const CLEAR_RESERVATION = 'CLEAR_RESERVATION';
export const REQUEST_LISTING_SEARCH_AUTOCOMPLETE = 'REQUEST_LISTING_SEARCH_AUTOCOMPLETE';

export const FETCH_FLIGHT_HOT_DEALS = 'FETCH_FLIGHT_HOT_DEALS';
export const RECEIVE_FLIGHT_HOT_DEALS = 'RECEIVE_FLIGHT_HOT_DEALS';

export const FETCH_HOTEL_HOT_DEALS = 'FETCH_HOTEL_HOT_DEALS';
export const RECEIVE_HOTEL_HOT_DEALS = 'RECEIVE_HOTEL_HOT_DEALS';

export const FETCH_BUS_HOT_DEALS = 'FETCH_BUS_HOT_DEALS';
export const RECEIVE_BUS_HOT_DEALS = 'RECEIVE_BUS_HOT_DEALS';

export const FETCH_TOUR_HOT_DEALS = 'FETCH_TOUR_HOT_DEALS';
export const RECEIVE_TOUR_HOT_DEALS = 'RECEIVE_TOUR_HOT_DEALS';

export const FETCH_ALL_HOT_DEALS = 'FETCH_ALL_HOT_DEALS';
export const RECEIVE_ALL_HOT_DEALS = 'RECEIVE_ALL_HOT_DEALS';

export const FETCH_VISA_HOT_DEALS = 'FETCH_VISA_HOT_DEALS';
export const RECEIVE_VISA_HOT_DEALS = 'RECEIVE_VISA_HOT_DEALS';

export const FETCH_CAR_HOT_DEALS = 'FETCH_CAR_HOT_DEALS';
export const RECEIVE_CAR_HOT_DEALS = 'RECEIVE_CAR_HOT_DEALS';

export const RECEIVE_HOTEL_API_NULL = 'RECEIVE_HOTEL_API_NULL';

//bus filter & sorts

export const LOAD_MORE_BUS = 'LOAD_MORE_BUS';
export const LOAD_BUS_DETAIL = 'LOAD_BUS_DETAIL';
export const RECEIVE_BUS_DETAIL = 'RECEIVE_BUS_DETAIL';
export const ADD_BUS_PRICE_FILTER = 'ADD_BUS_PRICE_FILTER';
export const RESET_BUS_PRICE_FILTER = 'RESET_BUS_PRICE_FILTER';

export const ADD_BUS_CLASS_FILTER   = 'ADD_BUS_CLASS_FILTER';
export const RESET_BUS_CLASS_FILTER =  'RESET_BUS_CLASS_FILTER';

export const ADD_BUS_DEPT_FILTER   = 'ADD_BUS_DEPT_FILTER';
export const RESET_BUS_DEPT_FILTER = 'RESET_BUS_DEPT_FILTER';

export const ADD_BUS_OPERATOR_FILTER   = 'ADD_BUS_OPERATOR_FILTER';
export const RESET_BUS_OPERATOR_FILTER = 'RESET_BUS_OPERATOR_FILTER';

export const ADD_BUS_AMENITIES_FILTER   = 'ADD_BUS_AMENITIES_FILTER';
export const RESET_BUS_AMENITIES_FILTER = 'RESET_BUS_AMENITIES_FILTER';

export const BUS_SORT_BY_EXPRESS = 'BUS_SORT_BY_EXPRESS';
export const BUS_SORT_BY_PRICE = 'BUS_SORT_BY_PRICE';
export const BUS_SORT_BY_DEPARTS = 'BUS_SORT_BY_DEPARTS';
export const BUS_SORT_BY_ARRIVAL = 'BUS_SORT_BY_ARRIVAL';
export const BUS_SORT_BY_DURATION = 'BUS_SORT_BY_DURATION';



export const FILTER_BUSES = 'FILTER_BUSES';

//end filter & sort 

//bus checkout 
export const SELECT_ONE_WAY_BUS = 'SELECT_ONE_WAY_BUS';
export const CONFIRM_BUS = 'CONFIRM_BUS';
export const RECEIVE_CONFIRM_BUS= 'RECEIVE_CONFIRM_BUS';
export const REQUEST_OWAY_TIER = 'REQUEST_OWAY_TIER';
export const RECEIVE_OWAY_TIER = 'RECEIVE_OWAY_TIER';
export const CHECK_OUT_CONFIRM_BUS = 'CHECK_OUT_CONFIRM_BUS';
export const RECEIVE_CHECKOUT_CONFIRM_BUS = 'RECEIVE_CHECKOUT_CONFIRM_BUS';
export const CREATE_BUS_BOOKING = 'CREATE_BUS_BOOKING';
export const RECEIVE_BUS_BOOKING = 'RECEIVE_BUS_BOOKING';
export const REQUEST_BUS_PAYMENT = 'REQUEST_BUS_PAYMENT';
export const RECEIVE_BUS_PAYMENT = 'RECEIVE_BUS_PAYMENT';

//bus order 
export const INSERT_BUS_ORDER = 'INSERT_BUS_ORDER';
export const RECEIVE_BUS_ORDER = 'RECEIVE_BUS_ORDER';
export const CONFIRM_BUS_ORDER = 'CONFIRM_BUS_ORDER';
export const RECEIVE_CONFIRM_BUS_ORDER = 'RECEIVE_CONFIRM_BUS_ORDER';
export const UPDATE_BUS_ORDER = 'UPDATE_BUS_ORDER';
export const RECEIVE_UPDATE_BUS_ORDER ='RECEIVE_UPDATE_BUS_ORDER';



//end bus checkout

//flight filter & sorts
export const ADD_STOP_FILTER = 'ADD_STOP_FILTER';
export const RESET_FLIGHT_STOP_FILTER = 'RESET_FLIGHT_STOP_FILTER';

export const ADD_PRICE_FILTER = 'ADD_PRICE_FILTER';
export const RESET_PRICE_FILTER = 'RESET_PRICE_FILTER';

export const ADD_AIRLILNENAME_FILTER = 'ADD_AIRLILNENAME_FILTER';
export const RESET_AIRLINENAME_FILTER = 'RESET_AIRLINENAME_FILTER';

export const ADD_DEPART_FILTER = 'ADD_DEPART_FILTER';
export const RESET_DEPART_FILTER = 'RESET_DEPART_FILTER';

export const ADD_TYPE_FILTER = 'ADD_TYPE_FILTER';
export const RESET_TYPE_FILTER = 'RESET_TYPE_FILTER';

export const ADD_CLASS_FILTER = 'ADD_CLASS_FILTER';
export const RESET_CLASS_FILTER = 'RESET_CLASS_FILTER';

export const SORT_BY_AIRLINE = 'SORT_BY_AIRLINE';

export const SORT_BY_DEURATION = 'SORT_BY_DEURATION';

export const SORT_BY_DEPART = 'SORT_BY_DEPART';

export const SORT_BY_ARRIVAL = 'SORT_BY_AIRLINE';

export const SORT_BY_PRICE = 'SORT_BY_PRICE';
// end of flight filter & sorts
export const LOAD_FLIGHT_LISTING_FROM_STORAGE = 'LOAD_FLIGHT_LISTING_FROM_STORAGE';
export const FILTER_FLIGHT_LISTING = 'FILTER_FLIGHT_LISTING';

export const REQUEST_TOUR_LISTING = 'REQUEST_TOUR_LISTING';
export const RECEIVE_TOUR_LISTING = 'RECEIVE_TOUR_LISTING';
export const RECEIVE_TOUR_LISTING_ERROR = 'RECEIVE_TOUR_LISTING_ERROR';
export const LOAD_MORE_TOUR = 'LOAD_MORE_TOUR';
export const RECEIVE_TOUR_LOAD_MORE = 'RECEIVE_TOUR_LOAD_MORE';
export const LOAD_TOUR_FILTER = 'LOAD_TOUR_FILTER';

export const ADD_TOUR_FILTER = 'ADD_TOUR_FILTER';
export const REDUCE_TOUR_FILTER = 'REDUCE_TOUR_FILTER';
export const RESET_TOUR_FILTER = 'RESET_TOUR_FILTER';

export const REQUEST_CATEGORY_FILTER = 'REQUEST_CATEGORY_FILTER';
export const RECEIVE_CATEGORY_FILTER = 'RECEIVE_CATEGORY_FILTER';

export const ADD_FILTER_CATEGORY = 'ADD_FILTER_CATEGORY';
export const REMOVE_FILTER_CATEGORY = 'REMOVE_FILTER_CATEGORY';
export const RESET_FILTERS_CATEGORY = 'RESET_FILTERS_CATEGORY';

export const REQUEST_SORT_PRICE_ASC = 'REQUEST_SORT_PRICE_ASC';
export const SORT_PRICE_ASC = 'SORT_PRICE_ASC';

export const REQUEST_SORT_PRICE_DEC = 'REQUEST_SORT_PRICE_DEC';
export const SORT_PRICE_DEC = 'SORT_PRICE_DEC';

export const REQUEST_TOUR_DETAIL = 'REQUEST_TOUR_DETAIL';
export const RECEIVE_TOUR_DETAIL = 'RECEIVE_TOUR_DETAIL'; 

export const REQUEST_SORT_DISCOUNT_ACE = 'REQUEST_SORT_DISCOUNT_ACE';
export const RECEIVE_SORT_DISCOUNT_ACE = 'RECEIVE_SORT_DISCOUNT_ACE';

export const REQUEST_SORT_DISCOUNT_DEC = 'REQUEST_SORT_DISCOUNT_DEC';
export const RECEIVE_SORT_DISCOUNT_DEC = 'RECEIVE_SORT_DISCOUNT_DEC';

export const REQUEST_SORT_RECOMMENDED_ACE = 'REQUEST_SORT_RECOMMENDED_ACE';
export const RECEIVE_SORT_RECOMMENDED_ACE = 'RECEIVE_SORT_RECOMMENDED_ACE';

export const REQUEST_SORT_RECOMMENDED_DEC = 'REQUEST_SORT_RECOMMENDED_DEC';
export const RECEIVE_SORT_RECOMMENDED_DEC = 'RECEIVE_SORT_RECOMMENDED_DEC';

export const REQUEST_ONEWAY_BUS_LISTING = 'REQUEST_ONEWAY_BUS_LISTING';
export const RECEIVE_ONEWAY_BUS_LISTING = 'RECEIVE_ONEWAY_BUS_LISTING';

export const REQUEST_ROUNDTRIP_BUS_LISTING = 'REQUEST_ROUNDTRIP_BUS_LISTING';
export const RECEIVE_ROUNDTRIP_BUS_LISTING = 'RECEIVE_ROUNDTRIP_BUS_LISTING';

export const RECEIVE_BUS_ERROR = 'RECEIVE_BUS_ERROR';

export const REQUEST_BUS_RETURN_LISTING = 'REQUEST_BUS_RETURN_LISTING';
export const RECEIVE_BUS_RETURN_LISTING = 'RECEIVE_BUS_RETURN_LISTING';

//country
export const REQUEST_COUNTRY = "REQUEST_COUNTRY";
export const RECEIVE_COUNTRY = "RECEIVE_COUNTRY";

//payment
export const REQUEST_PAYMENT_TYPE = "REQUEST_PAYMENT_TYPE";
export const RECEIVE_PAYMENT_TYPE = "RECEIVE_PAYMENT_TYPE";

//travellerInfo 
export const ADD_ADULT_TRAVELLER_INFO = "ADD_ADULT_TRAVELLER_INFO";
export const ADD_CHILD_TRAVELLER_INFO  = "ADD_CHILD_TRAVELLER_INFO";
export const ADD_INFANT_TRAVELLER_INFO  = "ADD_INFANT_TRAVELLER_INFO";

//order 
export const INSERT_ORDER = 'INSERT_ORDER';
export const SUCCESS_INSERT_ORDER = 'SUCCESS_INSERT_ORDER';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const SUCCESS_UPDATE_ORDER = 'SUCCESS_UPDATE_ORDER';
export const CONFIRM_ORDER = 'CONFIRM_ORDER';
export const SUCCESS_CONFIRM_ORDER = 'SUCCESS_CONFIRM_ORDER';
export const CONFIRM_ORDER_WITH_EMAIL = 'CONFIRM_ORDER_WITH_EMAIL';
export const SUCCESS_CONFIRM_ORDER_WITH_EMAIL = 'SUCCESS_CONFIRM_ORDER_WITH_EMAIL';
export const LOAD_ORDER_FROM_LOCAL_STORAGE= 'LOAD_ORDER_FROM_LOCAL_STORAGE';



//contactInfo
export const ADD_CONTACT_INFO = 'ADD_CONTACT_INFO';

//attraction
export const REQUEST_ATTR_LISTING = 'REQUEST_ATTR_LISTING';
export const RECEIVE_ATTR_LISTING = 'RECEIVE_ATTR_LISTING';
export const RECEIVE_ATTR_LISTING_ERROR = 'RECEIVE_ATTR_LISTING_ERROR';

export const REQUEST_ATTR_CATEGORY = 'REQUEST_ATTR_CATEGORY';
export const RECEIVE_ATTR_CATEGORY = 'RECEIVE_ATTR_CATEGORY';

export const LOAD_MORE_ATTR = 'LOAD_MORE_ATTR';
export const RECEIVE_ATTR_LOAD_MORE = 'RECEIVE_ATTR_LOAD_MORE';

export const REQUEST_ATTR_SORT_PRICE_ASC = 'REQUEST_ATTR_SORT_PRICE_ASC';
export const SORT_ATTR_PRICE_ASC = 'SORT_ATTR_PRICE_ASC';

export const REQUEST_ATTR_SORT_PRICE_DEC = 'REQUEST_ATTR_SORT_PRICE_DEC';
export const SORT_ATTR_PRICE_DEC = 'SORT_ATTR_PRICE_DEC';
 
export const REQUEST_ATTR_DETAIL = 'REQUEST_ATTR_DETAIL';
export const RECEIVE_ATTR_DETAIL = 'RECEIVE_ATTR_DETAIL';

export const REQUEST_ATTR_SORT_DISCOUNT_ACE = 'REQUEST_ATTR_SORT_DISCOUNT_ACE';
export const RECEIVE_ATTR_SORT_DISCOUNT_ACE = 'RECEIVE_ATTR_SORT_DISCOUNT_ACE';

export const REQUEST_ATTR_SORT_DISCOUNT_DEC = 'REQUEST_ATTR_SORT_DISCOUNT_DEC';
export const RECEIVE_ATTR_SORT_DISCOUNT_DEC = 'RECEIVE_ATTR_SORT_DISCOUNT_DEC';

export const REQUEST_ATTR_SORT_RECOMMENDED_ACE = 'REQUEST_ATTR_SORT_RECOMMENDED_ACE';
export const RECEIVE_ATTR_SORT_RECOMMENDED_ACE = 'RECEIVE_ATTR_SORT_RECOMMENDED_ACE';

export const REQUEST_ATTR_SORT_RECOMMENDED_DEC = 'REQUEST_ATTR_SORT_RECOMMENDED_DEC';
export const RECEIVE_ATTR_SORT_RECOMMENDED_DEC = 'RECEIVE_ATTR_SORT_RECOMMENDED_DEC';

export const ADD_ATTR_FILTER = 'ADD_ATTR_FILTER';
export const REDUCE_ATTR_FILTER = 'REDUCE_ATTR_FILTER';
export const RESET_ATTR_FILTER = 'RESET_ATTR_FILTER';

export const ADD_ATTR_FILTER_CATEGORY = 'ADD_ATTR_FILTER_CATEGORY';
export const REMOVE_ATTR_FILTER_CATEGORY = 'REMOVE_ATTR_FILTER_CATEGORY';

export const REQUEST_FILTER_TOUR_SEARCH = 'REQUEST_FILTER_TOUR_SEARCH';
export const RECEIVE_FILTER_TOUR_SEARCH = 'RECEIVE_FILTER_TOUR_SEARCH';

export const REQUEST_FILTER_ATTRACTION_SEARCH = 'REQUEST_FILTER_ATTRACTION_SEARCH';
export const REECEIVE_FILTER_ATTRACTION_SEARCH = 'REECEIVE_FILTER_ATTRACTION_SEARCH';

export const CLEAR_CHEKCOUT = 'CLEAR_CHEKCOUT';

// tour traveller info form
export const LOAD_TRAVELLER_INFO = 'LOAD_TRAVELLER_INFO';
export const CHANGE_FIRST_NAME_INPUT = 'CHANGE_FIRST_NAME_INPUT';
export const CHANGE_LAST_NAME_INPUT = 'CHANGE_LAST_NAME_INPUT';
export const CHANGE_COUNTRY_NAME_INPUT = 'CHANGE_COUNTRY_NAME_INPUT';
export const CHANGE_PASSPORT_NUMBER_INPUT = 'CHANGE_PASSPORT_NUMBER_INPUT';
export const CHANGE_EXPIRE_DATE_INPUT = 'CHANGE_EXPIRE_DATE_INPUT';

// tour traveller info form
export const CHANGE_CONTACT_FIRST_NAME = 'CHANGE_CONTACT_FIRST_NAME';
export const CHANGE_CONTACT_LAST_NAME = 'CHANGE_CONTACT_LAST_NAME';
export const CHANGE_CONTACT_PHONE_NO = 'CHANGE_CONTACT_PHONE_NO';
export const CHANGE_CONTACT_EMAIL = 'CHANGE_CONTACT_EMAIL';
export const CHANGE_CONTACT_ISINCLUDE = 'CHANGE_CONTACT_ISINCLUDE';
export const CHANGE_CONTACT_EASY_BOOK = 'CHANGE_CONTACT_EASY_BOOK';

// tour checkout 
export const REQUEST_CHECKOUT_CONFIRM = 'REQUEST_CHECKOUT_CONFIRM';
export const RECEIVE_CHECKOUT_CONFIRM = 'RECEIVE_CHECKOUT_CONFIRM';

export const REQUEST_ALL_CHECKOUT = 'REQUEST_ALL_CHECKOUT';
export const RECEIVE_ALL_CHECKOUT_RESPONSE = 'RECEIVE_ALL_CHECKOUT_RESPONSE';

export const RECEIVE_CHECKOUT_ERROR = 'RECEIVE_CHECKOUT_ERROR';
//Booking
export const REQUEST_PREPARE_BOOKING = 'REQUEST_PREPARE_BOOKING';
export const RECEIVE_PREPARE_BOOKING = 'RECEIVE_PREPARE_BOOKING';
export const REQUEST_COMPLETE_BOOKING = 'REQUEST_COMPLETE_BOOKING';
export const RECEIVE_COMPLETE_BOOKING = 'RECEIVE_COMPLETE_BOOKING';
export const LOAD_BOOKING_FROM_STORAGE = 'LOAD_BOOKING_FROM_STORAGE';


//makePayment
export const REQUEST_MAKE_PAYMENT = 'REQUEST_MAKE_PAYMENT';
export const RECEIVE_MAKE_PAYMENT = 'RECEIVE_MAKE_PAYMENT';

// tour booking
export const CREATE_TOUR_BOOKING = 'CREATE_TOUR_BOOKING';
export const RECEIVE_CREATE_TOUR_BOOKING = 'RECEIVE_CREATE_TOUR_BOOKING';

export const CREATE_TOUR_INSERT_ORDER = 'CREATE_TOUR_INSERT_ORDER';
export const RECEIVE_TOUR_INSERT_ORDER = 'RECEIVE_TOUR_INSERT_ORDER';

export const MAKE_TOUR_PAYMENT = 'MAKE_TOUR_PAYMENT';
export const RECEIVE_TOUR_PAYMENT_RES = 'RECEIVE_TOUR_PAYMENT_RES';

export const UPDATE_PAY_STATUS = 'UPDATE_PAY_STATUS';
export const UPDATE_PAY_STATUS_RES = 'UPDATE_PAY_STATUS_RES';

export const UPDATE_TOUR_BOOKING = 'UPDATE_TOUR_BOOKING';
export const UPDATE_TOUR_BOOKING_RES = 'UPDATE_TOUR_BOOKING_RES';

export const UPDATE_TOUR_ORDER = 'UPDATE_TOUR_ORDER';
export const UPDATE_TOUR_ORDER_RES = 'UPDATE_TOUR_ORDER_RES';

export const CONFIRM_TOUR_ORDER = 'CONFIRM_TOUR_ORDER';
export const CONFIRM_TOUR_ORDER_RES = 'CONFIRM_TOUR_ORDER_RES';
export const REQUEST_NEW_SLETTER = 'REQUEST_NEW_SLETTER';
export const RECEIVE_NEW_SLETTER = 'RECEIVE_NEW_SLETTER';

export const SENT_USER_SUBSCRIBE = 'SENT_USER_SUBSCRIBE';
export const RECEIVE_USER_SUBSCRIBE = 'RECEIVE_USER_SUBSCRIBE';
export const RECEIVE_ERROR_SUBSCRIBE = 'RECEIVE_ERROR_SUBSCRIBE';


//PAY_START
export const WAVE_PAY_START = 'WAVE_PAY_START';
export const SUCCESS_WAVE_PAY_START = 'SUCCESS_WAVE_PAY_STAR';
export const ONE_PAY_START = 'ONE_PAY_START';
export const SUCCESS_ONE_PAY = 'SUCCESS_ONE_PAY';
export const KBZ_PAY_START = 'KBZ_PAY_START';
export const SUCCESS_KBZ_PAY = 'SUCCESS_KBZ_PAY';
export const REQUEST_DAILY_RATE = 'REQUEST_DAILY_RATE';
export const RECEIVE_DAILY_RATE = 'RECEIVE_DAILY_RATE';

// hotel checkout
export const REQUEST_HOTEL_CHECKOUT = 'REQUEST_HOTEL_CHECKOUT';
export const RECEIVE_HOTEL_CHECKOUT = 'RECEIVE_HOTEL_CHECKOUT';

export const REQUEST_HOTEL_ORDER_INSERT = 'REQUEST_HOTEL_ORDER_INSERT';
export const RECEIVE_HOTEL_ORDER_INSERT = 'RECEIVE_HOTEL_ORDER_INSERT';

export const CREATE_HOTEL_ORDER = 'CREATE_HOTEL_ORDER';
export const RECEIVE_HOTEL_ORDER = 'RECEIVE_HOTEL_ORDER';

export const MAKE_HOTEL_PAYMENT = 'MAKE_HOTEL_PAYMENT';
export const RECEIVE_HOTEL_PAYMENT = 'RECEIVE_HOTEL_PAYMENT';

export const CHANGE_FIRST_NAME_HOTEL = 'CHANGE_FIRST_NAME_HOTEL';
export const CHANGE_LAST_NAME_HOTEL = 'CHANGE_LAST_NAME_HOTEL';
export const CHANGE_PHONE_NUM_HOTEL = 'CHANGE_PHONE_NUM_HOTEL';
export const CHANGE_EMAIL_INPUT_HOTEL = 'CHANGE_EMAIL_INPUT_HOTEL';
export const CHANGE_ALSO_TRAVELLING = 'CHANGE_ALSO_TRAVELLING';
export const CHANGE_ADULT_NAME = 'CHANGE_ADULT_NAME';
export const CHANGE_ADULT_LAST_NAME = 'CHANGE_ADULT_LAST_NAME';
export const CHANGE_ADD_PHONE_NUM = 'CHANGE_ADD_PHONE_NUM';
export const CHANGE_COUNTRY_NAME = 'CHANGE_COUNTRY_NAME';
export const CHANGE_PASSPORT_NUM_HOTEL = 'CHANGE_PASSPORT_NUM_HOTEL';

export const RECEIVE_PAY_UPDATE = 'RECEIVE_PAY_UPDATE'
export const RECEIVE_HOTEL_ORDER_UPDATE = 'RECEIVE_HOTEL_ORDER_UPDATE'
export const RECEIVE_HOTEL_ORDER_CONFIRM = 'RECEIVE_HOTEL_ORDER_CONFIRM'

export const ALERT_MSG = 'ALERT_MSG';
export const REQUEST_HOTEL_ALL_CHECKOUT = 'REQUEST_HOTEL_ALL_CHECKOUT';
export const RECEIVE_HOTEL_ALL_CHECKOUT = 'RECEIVE_HOTEL_ALL_CHECKOUT';

// myanmar visa

export const REQUEST_VISA_SEARCH = 'REQUEST_VISA_SEARCH';
export const RECEIVE_VISA_SEARCH = 'RECEIVE_VISA_SEARCH';
export const APPLY_VISA = 'APPLY_VISA';
export const RECEIVE_APPLY_VISA = 'RECEIVE_APPLY_VISA';
export const REQUEST_VISA_CHECKOUT = 'REQUEST_VISA_CHECKOUT';
export const RECEIVE_VISA_CHECKOUT = 'RECEIVE_VISA_CHECKOUT';

/**
 * user action
 */

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN';
export const RECEIVE_USER_LOGIN = 'RECEIVE_USER_LOGIN';
export const RECEIVE_USER_LOGIN_ERR = 'RECEIVE_USER_LOGIN_ERR';
export const VERIFY_USER_OTP = 'VERIFY_USER_OTP';
export const VERIFY_USER_OTP_RES = 'VERIFY_USER_OTP_RES';
export const VERIFY_USER_OTP_ERR = 'VERIFY_USER_OTP_ERR';
export const REQUEST_USER_REGISTER = 'REQUEST_USER_REGISTER';
export const RECEIVE_USER_REGISTER = 'RECEIVE_USER_REGISTER';
export const RECEIVE_USER_REGISTER_ERR = 'RECEIVE_USER_REGISTER_ERR';
export const RECEIVE_OTP_CONFIRM = 'RECEIVE_OTP_CONFIRM';
export const HIDE_OTP = 'HIDE_OTP';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_RES = 'FORGOT_PASSWORD_RES';
export const REQUEST_CHANGE_PASSWORD = 'REQUEST_CHANGE_PASSWORD';
export const RECEIVE_CHANGE_PASSWORD = 'RECEIVE_CHANGE_PASSWORD';
